src/web3-adapter/alchemyContext.ts

Increase the limit on message size when running in Node by bumping the
limit in the  `websocket` library from 1MB to 100MB.  This matches the
default of the similar `ws` library and is more inline with browsers
which allows such sizes.

Increase WebSocket frame limit on Node

---

src/subscriptions/subscriptionBackfill.ts
src/util/promises.ts
src/web3-adapter/webSocketProvider.ts
test/subscriptionBackfill.test.ts

If the websocket fails again during backfill, the backfill process
should be terminated and start up again when a new socket is available.
This cleans up an error case in which the backfill would fail and not
clean up after itself, leaving the subscription in a dead state.

Cancel backfill if the socket goes down

---

src/subscriptions/subscriptionBackfill.ts
src/web3-adapter/webSocketProvider.ts

Our subscriptions need to store events they have sent recently so if
they need to be reconnected we can detect re-orgs that occurred while
they are down. These events were previously stored in buffers that grew
without bound. Now make sure to evict old values that we no longer need.

Avoid a memory leak when storing past events

---

src/web3-adapter/alchemyContext.ts
src/web3-adapter/sendPayload.ts

Fixes a bug caused by Web3's checking of response ids clashing with our
payload generation function. Rather than generating our own payloads
based on the method and params of the request, we pass along Web3's
payload unchanged.

Fix "Wrong response id" error on write provider

---

src/util/promises.ts

Cleans up an unintended interaction when handling Node-style callback
that return rejected promises. Such callbacks would lead to "unhandled
promise rejection" messages in our utility function `callWhenDone`.

Avoid spurious "unhandled promise rejection" messages

---

README.md
src/index.ts

We added ordering to the getAssetTransfers API recently this PR exposes the order parameter to our api.
This pull request adds a parameter to the exiting alchemy_getAssetTransfers method to our Alchemy Web 3 client.
*Test using order permutations and ensuring results return*

Add Order to Get Asset Transfers Alchemy Web3

---

src/index.ts

Fixes a type error on the nit metadata response internal object. [(Context)](https://alchemyinsights.slack.com/archives/C02L0TDK48N/p1639530301116400)
**Note for reviewers:** Interestingly the data that was returned just fine in both the before and after this fix. So before just blindly shipping this I'm going to investigate why. But I thought getting the fix out there earlier the better for review.
^ Update: Because our web3 playground evaluates all of the types from the library to any and the `callAlchemyMethod` in the web3 function just does a straight pass-through from the backend result the data would correctly propagate through in the test. _However, any consumers of the api could have a compiler error trying to access the objects in a real library given the types wouldn't match …

Update type for nft metadata response

---

src/alchemy-apis/types.ts
src/index.ts
src/subscriptions/subscriptionBackfill.ts
src/types.ts
src/util/jsonRpc.ts
src/web3-adapter/alchemyContext.ts
src/web3-adapter/alchemySend.ts
src/web3-adapter/alchemySendHttp.ts
src/web3-adapter/alchemySendWebSocket.ts
src/web3-adapter/httpProvider.ts
src/web3-adapter/sendJsonRpcPayload.ts
src/web3-adapter/sendRestPayload.ts
src/web3-adapter/webSocketProvider.ts
test/alchemySubscriptions.test.ts
test/subscriptionBackfill.test.ts
test/websocketProvider.test.ts
yarn.lock

This adds support for 2 new rest endpoints: getNfts and getNftMetadata. Since these two endpoints are REST and not jsonRpc, I have also renamed a lot of variables to include jsonRpc for clarity. I have also added support for retries on 429 rate limit responses. Also note that these new REST endpoints only work with the new alchemy.com endpoints, not legacy alchemyapi.io endpoints.

Add a REST handler for getNfts and getNftMetadata

---

package.json
src/web3-adapter/sendRestPayload.ts
yarn.lock

This is to support React Native, which doesn't support the standard
`URL` API which is available in both browsers and Node.

Use urijs instead of native URL

---

README.md
src/alchemy-apis/types.ts
src/index.ts
src/web3-adapter/alchemySendHttp.ts

Adds [TransactionRecipts API](https://docs.alchemy.com/alchemy/enhanced-apis/transaction-receipts-api).
Tested npm package locally on dummy app:
```ts
web3.alchemy
.getTransactionReceipts({ blockNumber: "0xd796e0" })
.then((res: TransactionReceiptsResponse) => {
console.log(res);
});
web3.alchemy
.getTransactionReceipts({ 
blockHash:
"0x15481e27761bc2776c2cd82176f5d11d5ad0f0d33c26b657db3e9f5745864a18"
})
.then((res: TransactionReceiptsResponse) => {
console.log(res);
});
```
Resulting output (truncated):
```
{
receipts: [
{
transactionHash: '0x38c46226dc90b42689a520f880e92182b324c46be2f76bdbcd679e259b9c0db9',
blockHash: '0xd206645a625d7974ec3a54203fa23548b602c5e8e3c24eb74464bc911ad95aeb',
blockNumber: '0xd796e0',
contractAddress: null,
cumulativeGasUsed: '0x5208',
effectiveGasPrice: …
```

add getTransactionReceipts alchemy endpoint

---

README.md
src/index.ts

The current API surface does not allow for specifying all tokens via `DEFAULT_TOKENS` in `getTokenBalances()` when writing in TS since `contractAddresses: string[]` does not allow for raw string inputs.
This PR adds the ability to fetch all tokens for a given address by omitting `contractAddresses`.
1. Omit `contractAddresses`
- Call: `web3.alchemy.getTokenBalances("0xc01512D16109e0913241B54fCbdc572AcDc90695")`
- Output: 
```
{
address: '0xc01512D16109e0913241B54fCbdc572AcDc90695',
tokenBalances: [
{
contractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
tokenBalance: '0',
error: null
},
{
contractAddress: '0x15d4c048f83bd7e37d49ea4c83a07267ec4203da',
tokenBalance: '0',
error: null
},
...
]
}
```
2. Empty `contractAddresses` array (matches Composer behavior)
- Call: …

getTokenBalances: allow specifying "DEFAULT_TOKENS" by omitting contractAddresses param

---

src/web3-adapter/sendRestPayload.ts

- Remove error message when using still-functional alchemyapi.io server
as the API
<hr/>
Hello all! I am a new alchemy user, and I just started running into an error while using this library.
This change was introduced in commit `bbeed08` just before the `1.1.11` release, and I started doing development with the library just this week. 
On my dashboard, I am given an alchemy url which points to `alchemyapi.io`, and there are no visible alternatives which match the suggested `alchemy.com` endpoints. As a user, I find it confusing that the URL given on my site doesn't match the URL which is accepted by the library.
Furthermore, switching my url to point to `alchemy.com` doesn't appear to be working for me (requests time out), and this library functions 100% perfectly if I just apply this …

Remove error when using alchemyapi.io API

---

src/index.ts
src/web3-adapter/alchemyContext.ts

We previously checked if a URL was an Alchemy URL by seeing if it
contained `alchemyapi.io`, our old domain. We now accept `alchemy.com`,
our new domain, as well.
This only affects metrics/logging.

Accept alchemy.com as an Alchemy URL

---

src/web3-adapter/sendRestPayload.ts

While we transition towards the new `alchemy.com` endpoints rather than
`alchemyapi.io` endpoints, we are ready to fully transition on L2
networks but not yet on eth networks. For now, allow eth networks to
keep using the old endpoints but require the new endpoints for L2s.

Disallow legacy endpoints on L2 networks

---

src/alchemy-apis/types.ts

Fixes #96.
Main change is to use types that match our backend's response types, rather than the default Web3.js types.
Tested in dummy app to check matching types. Also referenced ethers.js [types](https://github.com/ethers-io/ethers.js/blob/master/packages/abstract-provider/src.ts/index.ts#L89) for `TransactionReceipt` to check log types.

Update TransactionReceipt type to match backend types

---

README.md
src/alchemy-apis/types.ts
src/index.ts

Fixes #99, Fixes #101.
This PR adds the `withMetadata` param to `getNfts()` and updates the return types to include the NFT metadata by default. This means that this PR should only be merged after @niveda-krish's changes to make `withMetadata=true` the default are pushed to prod.
I separated out `GetNftsResponse` to`GetNftsResponseWithoutMetadata` to give developers an easier way to reason about the types when `withMetadata` is set to `false`. 
I initially wanted to have two overloads for `withMetadata=false` and the default case in order to have better type completion. However, since the methods are defined on an object, I don't think overloads are possible. I'd be down to explore refactoring the methods into a separate class.
I verified manually that changes compile and ran a few API …

Add withMetadata typings and metadata response types for getNFTs()

---

src/web3-adapter/sendJsonRpcPayload.ts

Fixes #62.
Turns out we're forwarding calls prefixed with `personal_` to the Alchemy provider, when they should instead be handled instead by the default writer provider. This PR makes forwards all calls prefixed with `personal_` to the write provider, since Alchemy does not support them.

add personal_ to disallow prefix

---

package.json
yarn.lock

Small change to upgrade our web3.js dependency to give devs some QoL fixes.

Upgrade web3.js from 1.6.0 to 1.7.1 (latest)

---

src/alchemy-apis/types.ts

Fixes #116.
Small naming correction. Verified response property name is `contractAddress` after testing the endpoint.

Fix contractAddress property on TokenBalanceSuccess and TokenBalanceFailure

---

src/alchemy-apis/types.ts

A call to `getNftMetadata` should return the full `Nft` object that contains an optional `NftMetadata` object. This also matches the backend response types.

Fix GetNftMetadataResponse typing

---

src/alchemy-apis/types.ts

Seems like the `balance` field returns when possible on a `BaseNft` object, through both the `getNFTs` call (with or without metadata). This is useful for determining the amount of the tokenId when referencing an `erc1155`. 
Adding this type makes it so that typescript does not throw errors.
Btw, is there a difference between `v1` and `v2` api? https://github.com/alchemyplatform/alchemy-web3/blob/1381e8e2183b6a11c98c008ba5c73cd11e8cd2c7/src/index.ts#L176. Current documentation on https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/getnfts references `v2`. 
Thanks for this useful library!

Add balance field to BaseNft

---

src/index.ts
src/types.ts
src/web3-adapter/sendJsonRpcPayload.ts

Hello, thank you for this useful library. We were using ethers.js to listen to new logs on blockchain, but due to occasional websocket disconnection, we made research for solutions and found this library and decided to use it. Now we want to add our functionalities to the alchemy-web3 provider. Functionalities like monitoring, caching, I mean, middleware things. To do so, we added middleware support to the library. So now we can monitor our outgoing/incoming ws/http messages and cache them.
Example middleware for monitoring:
```ts
...
createJsonRpcSenderMiddleware = (): JsonRpcSenderMiddleware => {
return (request, next) => {
const startedTime = Date.now();
this.emit('request', request);
return next().then((response) => {
const executionTime = Date.now() - startedTime; …
```

Add middleware support

---

src/index.ts

The Alchemy NFT endpoint was switched to v2 in a previous PR, but the `alchemyapi.io` endpoints only support `v1`. v2 only exists on `g.alchemy.com`. 
Undoing the change here.

Revert back to v1 on endpoint

---

src/index.ts

Fixes #74.
`web3-eth-abi` only exports the `AbiEncoder` class and not the `decodeParameter` function, so the resulting bundle was unable to locate the export. You can test this out on `v1.4.3-beta`

Fix improper AbiEncoder.decodeParameter() import

---

src/index.ts

The return value of the subscription type alchemy_filteredFullPendingTransactions should contain the Trasaction type

Fix the missing Transaction in the return type of subscribe

---

src/index.ts
src/types.ts

Adding support for the new `alchemy_pendingTransactions` endpoint ([docs](https://docs.alchemy.com/alchemy/enhanced-apis/subscription-api-websockets#alchemy_pendingtransactions)). 
- Using the old subscription endpoints will now log a deprecated warning.
- Includes an overload for the `{hashesOnly: true}` return type.
Verified in dummy test app.
Fixes #138

Add alchemy_pendingTransactions support

---

src/alchemy-apis/types.ts

Fixes #144.
Updates `getAssetTransfers()` to reflect the [changelog](https://docs.alchemy.com/alchemy/documentation/changelog#06-27-2022)

Require 'category' field in getAssetTransfers()

---

README.md

As of July 2022, this repo is now in maintenance mode. The new SDK based on ethers.js is now available on [GitHub](https://github.com/alchemyplatform/alchemy-sdk-js) or [NPM](https://www.npmjs.com/package/alchemy-sdk). It has feature parity with this library as well as better typing, more abstractions, and more documentation.
Going forward, updates to this library will be made on a best-effort basis. If you see a bug or have a feature request, please open an issue or pull request on the [Github issues](https://github.com/alchemyplatform/alchemy-web3/issues) section.

Update README to reflect maintenance mode

---

README.md
package.json
src/index.ts
src/web3-adapter/sendRestPayload.ts
yarn.lock

This fixes the NFT endpoints by updating to the `v2` endpoint URLs and updates the latest version of web3.js.

Fix NFT endpoints and update web3.js
